name: Dayly Download ABR CSVs

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # GITHUB_TOKENでpushできるように

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # pushのために必要

      - name: Run download script
        run: |
          chmod +x download.sh
          ./download.sh

      - name: Commit and push if changes exist
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "update: $(date '+%Y-%m-%d')"
            git pull --rebase
            git push origin HEAD
          else
            echo "No changes to commit."
          fi
